---
# tasks file for ansible-nginx
- name: Include OS-specific variables.
  include_vars: "{{ ansible_os_family }}.yml"
  tags:
    - apache

- include: install-debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - apache

- include: install-centos.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - apache

- name: Get installed version of Apache.
  shell: "{{ apache_daemon }} -v"
  changed_when: false
  always_run: yes
  register: _apache_version
  tags:
    - apache

- name: Create apache_version variable.
  set_fact:
    apache_version: "{{ _apache_version.stdout.split()[2].split('/')[1] }}"
  tags:
    - apache

- name: Create apache_version variable.
  set_fact:
    apache_version_slim: "{{apache_version.split('.')[0]}}.{{apache_version.split('.')[1]}}"
  tags:
    - apache

- name: Include apache specific vars
  include_vars: apache-{{ apache_version_slim }}.yml
  tags:
    - apache

- name: Disable Apache mods.
  file:
    path: "{{ apache_server_root }}/mods-enabled/{{ item }}"
    state: absent
  with_items: apache_mods_disabled
#  notify: restart apache
  tags:
    - apache

- name: Enable Apache modules
  file:
    src={{ apache_server_root }}/mods-available/{{ item }}
    dest={{ apache_server_root }}/mods-enabled/{{ item }}
    state=link
  with_items: apache_mods_enabled
#  notify: restart apache
  tags:
    - apache



- name: Remove default vhost in sites-enabled.
  file:
    path: "{{ apache_default_vhost_filename }}"
    state: absent
  notify: restart apache
  when: apache_remove_default_vhost
  changed_when: false
  tags:
    - apache

- name: copy apache default conf
  template: src=ports.conf.j2 dest={{ apache_server_root }}/ports.conf
#  notify: restart apache
  tags:
    - apache


- name:  Create directories for sites available/enabled.
  file:
    path: "{{ apache_default_vhost_filename }}"
    state: directory
  changed_when: false
  with_items:
    - "{{apache_sites_available_path}}"
    - "{{apache_sites_enabled_path}}"

  tags:
    - apache

- name:  Create documentroot of sites
  file:
    path: "{{  item.documentroot }}"
    state: directory
  changed_when: false
  when: item.documentroot is defined
  with_items: apache_vhosts
  tags:
    - apache

- name: Add apache vhosts configuration.
  template:
    src: "vhosts-{{ apache_version_slim }}.conf.j2"
    dest: "{{ apache_default_vhost_filename }}"
    owner: root
    group: root
    mode: 0644
  notify: restart apache
  when: apache_create_vhosts
  changed_when: false
  tags:
    - apache

- name: Configure Apache to  include sites-enabled.
  lineinfile:
    dest={{ apache_server_root  }}/conf/{{ apache_daemon }}.conf
    regexp="^Include sites-enabled"
    line="Include sites-enabled/*"
    state=present
  tags:
    - apache

#
#- include_vars: apache-22.yml
#  when: "apache_version.split('.')[1] == '2'"
#
#- include_vars: apache-24.yml
#  when: "apache_version.split('.')[1] == '4'"

- include: configure-debian.yml
  when: "ansible_os_family == 'Debian'"
  tags:
    - apache

- include: configure-centos.yml
  when: "ansible_os_family == 'RedHat'"
  tags:
    - apache

