---
- name: install apache packages
  apt: pkg={{ item }} state=latest update_cache=yes cache_valid_time=86400
  with_items: apache.apache_packages
  tags:
    - apache

- name: copy apache default conf
  template: src=ports.conf.j2 dest={{ apache.server_root }}/ports.conf
  notify: reload apache
  tags:
    - apache


- name: Enable Apache mods (Debian).
  file:
    src={{ apache.server_root }}/mods-available/{{ item }}
    dest={{ apache.server_root }}/mods-enabled/{{ item }}
    state=link
  with_items: apache.mods_enabled
  notify: restart apache
  tags:
    - apache
