---
- name: install apache packages
  yum: pkg={{ item }} state=installed
  with_items: apache.apache_packages
  tags:
    - apache

- name: copy apache default conf
  template: src=ports.conf.j2 dest={{ apache.server_root }}/ports.conf
  notify: reload apache
  tags:
    - apache


