---
# handlers file for ansible-apache
- name: restart apache
  service:
    name: "{{ apache_daemon }}"
    state: restarted
  when: apache_use_service|bool

- name: reload apache
  service:
    name: "{{ apache_daemon }}"
    state: reloaded
  when: apache_use_service|bool
